- .eslintrc.json
- src/web/app/actions/beambox/preview-mode-controller.ts
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/views/beambox/Camera-Calibration.tsx
- src/web/interfaces/ILang.d.ts
> Add use last config button in Camera Calibration

- public/js/lib/svgeditor/recalculate.js
- src/web/app/actions/beambox/export-funcs.ts
- src/web/app/actions/global.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/helpers/file-export-helper.ts
- src/web/helpers/units.ts
See notion BX-215
Also fixed
1. Recalculate with transfom: [R][M], 
2. Change Text Command when no element is provided,
3. Global.ts popstate event disabled some shortcuts.
> Fix exported svg file size

- src/web/helpers/auto-save-helper.ts
See notion BX-209
Try to prompt mac permission
> Add a dumb file when initing auto-save-helper

- src/web/app/contexts/Monitor-Context.tsx
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/views/dialogs/Prompt.tsx
- src/web/helpers/device-master.ts
- src/web/interfaces/ILang.d.ts
See BX-223. (commit b7b8ee5)
Also fixed:
1. monitor behavior when connection has broken. (commit 7bcd3f2)
2. Prompt refs error. BXv1.6.2-09 (commit 75094fb)
3. unit2Pixel fallback (commit db1ee73)
> Improve pathAction.fixEnd speed

- src/web/app/actions/beambox/font-funcs.ts
- src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
- src/web/app/views/settings/Setting-General.tsx
- src/web/interfaces/IFont.d.ts
> Remove TextbyFluxsvg option from general settings

- src/web/app/actions/beambox/font-funcs.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
- src/web/helpers/api/svg-laser-parser.ts
- src/web/helpers/pdf-helper.ts
- src/web/helpers/symbol-maker.ts
Fixed:
1. BXv1.6.2-01: Text actions related bug. (92a6fe4)
2. BXv1.6.2-04: symbol-maker jquery related bug. (86ea3e1)
3. BXv1.6.2-06: pdf-helper webpack related bug. (7e1791d)
4. BXv1.6.2-07: text-to-path bugs (3ba7525)
> Fix 1.6.2 alpha verification bugs

- src/web/app/contexts/Monitor-Context.tsx
- src/web/app/views/monitor/Monitor-Header.tsx
- src/web/app/views/monitor/Monitor.tsx
> Add nav back button when aborted or completed

- src/web/app/contexts/Alert-Progress-Context.tsx
- src/web/app/views/dialogs/Alerts-And-Progress.tsx
- src/web/helpers/api/svg-laser-parser.ts
- src/web/interfaces/IAlert.d.ts
prevent animation from replaying (35aa8c0).
See notion BXv1.6.2-03
> Update Alert-And-Progress children key

- src/web/app/actions/beambox/beambox-global-interaction.ts
- src/web/app/actions/beambox/beambox-init.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/views/settings/Setting-General.tsx
- src/web/helpers/menubar/electron-menubar-helper.ts
- src/web/helpers/menubar/view.ts
- src/web/helpers/pdf-helper.ts
- src/web/interfaces/ILang.d.ts
Add anti-aliasing setting & Split view menu functions to another file.
See BX-231
> Add anti-aliasing setting

- public/js/lib/svgeditor/coords.js
- public/js/lib/svgeditor/math.js
- src/web/app/svgedit/svgcanvas.ts
- src/web/helpers/menubar/electron-menubar-helper.ts
- src/web/helpers/menubar/view.ts
Improve disassemble performance: see BX-233 (f7982b3)
Truncate decimal number after calculating position: see BX-234 (f3ffde4)
Also fixed: electron-menubar-helper errors: (18d9148, d81952d)
> Improve disassemble & rendering performance

- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
> Add translation excepts rating

- src/web/app/svgedit/svgcanvas.ts
> Improve handleHistoryEvent time performance

- src/web/app/views/beambox/Photo-Edit-Panel.tsx
As title.
Feedback from 1.7.0 alpha testing.
> Update sharpen panel default value

- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
> Update #845 message

- src/web/app/views/dialogs/Change-Log.tsx
> Update change log, allow breakline

- src/web/app/views/beambox/Photo-Edit-Panel.tsx
- src/web/helpers/image-data.ts
Fixed Notion BXv1.7.0-13: Cropping container bug when going back (50a6bf8)
Fixed Notion BX-238: Image cropping bug when image is big (b35db34)
> Fix image cropping related bugs

- src/web/app/views/beambox/Photo-Edit-Panel.tsx
> Refine photo-edit-panel syntax

- src/web/app/views/beambox/Right-Panels/Laser-Manage-Modal.tsx
- src/web/app/views/dialogs/Alerts-And-Progress.tsx
- src/web/app/widgets/Alert.tsx
- src/web/interfaces/ILaserConfig.d.ts
> Blur active element when alert popup

- package.json
- src/implementations/sentry.ts
- src/web/helpers/sentry-helper.ts
> Add sentry interface

- src/web/helpers/api/flux-id.ts
- src/web/helpers/api/open-cv.ts
- src/web/helpers/rating-helper.ts
> Fix ts errors

- src/web/app/contexts/Monitor-Context.tsx
as title.
Avoiding alerts keep popping.
> Avoid monitor getReport before last one not ended

- src/implementations/os.ts
- src/web/app/views/beambox/Network-Testing-Panel.tsx
- src/web/app/views/beambox/Photo-Edit-Panel.tsx
- src/web/helpers/output-error.ts
- src/web/helpers/smart-upnp.ts
- src/web/interfaces/IOperatingSystem.d.ts
As title.
Also fixed photo-edit-panel cropping bug.
> Fix requirenode os

- src/web/app/actions/beambox/font-funcs.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/svgedit/history.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/svgedit/textactions.ts
- src/web/app/svgedit/textedit.ts
- src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
- src/web/app/views/beambox/Right-Panels/Options-Blocks/Text-Options.tsx
- src/web/interfaces/IHistory.d.ts
Seperate textActions to `textaction.ts` and other edit function to `textedit.ts`.
> Seperate text related function from svgcanvas

- src/web/interfaces/IFont.d.ts
> Add type FontDescriptorKeys

- src/web/app/actions/beambox/beambox-global-interaction.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/svgedit/operations/clipboard.ts
- src/web/app/svgedit/operations/delete.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/svgedit/textactions.ts
- src/web/app/widgets/Curve-Control.tsx
Move clipboard functions and delete out from svgcanvas.ts
> Move clipboard functions and delete  out

- src/web/app/actions/beambox/beambox-init.ts
- src/web/app/actions/beambox/export-funcs.ts
- src/web/app/contexts/Monitor-Context.tsx
- src/web/app/views/beambox/Right-Panels/Actions-Panel.tsx
- src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
- src/web/helpers/file-export-helper.ts
- src/web/helpers/output-error.ts
- src/web/interfaces/IDialog.d.ts
Update dialog interface for web version app.
Should be used with https://github.com/flux3dp/beam-studio-web/pull/11 & https://github.com/flux3dp/beam-studio/pull/133
> Update dialog interface for web version

- src/web/app/actions/beambox/svg-editor.ts
Caused by (e14d2e7) Uncompleted selector deletion.
> Fix web workarea size bug

- src/web/helpers/api/camera.ts
Fix some camera previewing error resulting from transmit fail judgement.
> Update camera transmit fail judging

- src/web/app/actions/beambox/beambox-preference.spec.ts
- src/web/app/actions/beambox/beambox-preference.ts
- src/web/app/actions/beambox/constant.ts
- src/web/app/constants/right-panel-constants.ts
- src/web/app/views/beambox/Diode-Calibration.tsx
- src/web/helpers/device-master.ts
Update diode default offset & preset
> Update diode default

- src/web/app/actions/beambox/svg-editor.ts
Fix import js failed.
use Function to replace require
> Fix import js

- src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.spec.tsx
- src/web/app/views/beambox/Right-Panels/contexts/ObjectPanelController.tsx
> Fix ObjectPanelController getDimensionValues

- package.json
- src/web/app/actions/beambox/menuActions.ts
- src/web/app/views/beambox/TopBar/Menu.spec.tsx
- src/web/app/views/beambox/TopBar/Menu.tsx
- src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
- yarn.lock
https://github.com/feross/buffer
> 1. import a new blob lib which is compatible for both web and Node 2. implement importing examples 3. fix tests

- src/web/app/actions/beambox/font-funcs.ts
- src/web/helpers/beam-file-helper.ts
- src/web/helpers/file-export-helper.ts
allow save as beam, readBeam for web
> Beam read/write for web

- src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
- src/web/app/views/beambox/TopBar/Menu.spec.tsx
- src/web/app/views/beambox/TopBar/Menu.tsx
- src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
- src/web/helpers/shortcuts.ts
- src/web/setupTests.ts
2. minor tuning to make code work in both platforms
> 1. remove unnecessary menu item disabled

- src/web/app/pages/Home.tsx
- src/web/helpers/api/svg-laser-parser.ts
- src/web/helpers/menubar/AbstractMenu.ts
Update AbstractMenu & Remove electron in Home.tsx
> Remove electron in home

- src/web/app/svgedit/history.ts
- src/web/app/svgedit/svgcanvas.ts
> Fix undo/redo related bugs

- src/web/app/constants/hotkeys.ts
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/views/beambox/TopBar/Menu.spec.tsx
- src/web/app/views/beambox/TopBar/Menu.tsx
- src/web/app/views/beambox/TopBar/__snapshots__/Menu.spec.tsx.snap
- src/web/app/views/settings/General.spec.tsx
- src/web/app/views/settings/General.tsx
- src/web/app/views/settings/SettingGeneral.tsx
- src/web/app/views/settings/Update.spec.tsx
- src/web/app/views/settings/Update.tsx
- src/web/app/views/settings/__snapshots__/General.spec.tsx.snap
- src/web/app/views/settings/__snapshots__/Update.spec.tsx.snap
- src/web/interfaces/ILang.d.ts
1. add a new hot key for connection type selection page
2. refactor hotkey structure
3. remove dev tool menu item
4. remove notification and auto check update preferences for web version
> multiple changes

- src/web/app/views/beambox/TopBar/CommonTools.spec.tsx
- src/web/app/views/beambox/TopBar/CommonTools.tsx
- src/web/app/views/beambox/TopBar/TopBar.tsx
- src/web/app/views/beambox/TopBar/__snapshots__/CommonTools.spec.tsx.snap
use the arbitrary image to complete the function first; css will be fixed once the images are given afterwards
> add undo and redo at topbar

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/actions/beambox/svgeditor-function-wrapper.ts
- src/web/app/views/beambox/LeftPanel/LeftPanel.tsx
- src/web/setupTests.ts
fix windows open dialog default path.
> Update import image, using dialog

- src/web/app/pages/Beambox.tsx
- src/web/app/views/beambox/Path-Preview.tsx
- src/web/app/views/beambox/TopBar/TopBar.tsx
Replace lookbehind for safari, which does not support this syntax
> Fix path preview related bug

- src/web/app/svgedit/touchEvents.spec.tsx
- src/web/app/svgedit/touchEvents.ts
Add touch event delay to avoid two point touch trigger mouse down event
> Add touch event delay

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/actions/dialog-caller.tsx
- src/web/app/components/beambox/top-bar/GoButton.tsx
- src/web/app/components/dialogs/FluxIdLogin.tsx
- src/web/app/components/dialogs/__snapshots__/FluxIdLogin.spec.tsx.snap
- src/web/helpers/api/flux-id.ts
force login only when exporting
> Update force login in web

- public/js/lib/svgeditor/svgutils.js
- src/web/app/components/dialogs/MediaTutorial.spec.tsx
- src/web/app/components/dialogs/MediaTutorial.tsx
- src/web/app/components/dialogs/__snapshots__/MediaTutorial.spec.tsx.snap
- src/web/app/constants/media-tutorials.ts
- src/web/app/svgedit/textactions.ts
- src/web/app/svgedit/textedit.ts
- src/web/app/views/beambox/Camera-Calibration.tsx
- src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
- src/web/interfaces/ITutorial.d.ts
1. add fallback videos for browsers not supporting webm.
2. fix text edit display bug in safari.
3. disable image sharpen when no ghost connection.
> Fixes for web2

- src/web/helpers/file-export-helper.ts
remove `clip-path` in layer elements
> Fix export as svg

- src/web/app/svgedit/svgcanvas.ts
as title.
use querySelectAll instead.
> Fix jquery find max call stack issue

- src/web/app/components/beambox/path-preview/PathPreview.tsx
> Fix path preview start here fcode

- src/web/app/components/dialogs/AboutBeamStudio.spec.tsx
- src/web/app/components/dialogs/AboutBeamStudio.tsx
- src/web/app/components/dialogs/__snapshots__/AboutBeamStudio.spec.tsx.snap
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/views/beambox/Right-Panels/Laser-Panel.tsx
- src/web/interfaces/ILang.d.ts
as title
https://app.clickup.com/t/3hhpr7r
https://app.clickup.com/t/24pu583
> Add low power warning & Update copyright year

- src/web/app/svgedit/operations/clipboard.ts
- src/web/app/svgedit/operations/delete.ts
https://app.clickup.com/t/3h633zu
> Fix replicated <use> color issue

- src/web/app/components/beambox/top-bar/TopBar.tsx
as title 
https://app.clickup.com/t/3hhqz38
> Fix top bar layout issue

- src/web/app/actions/beambox/preview-mode-controller.ts
https://app.clickup.com/t/3jtjkmt
> Handle error when takeOnePicture return undefined

- src/web/app/svgedit/operations/clipboard.ts
https://flux3dp.slack.com/archives/C03EYFTC1/p1665982306980509
> Fix pasted use element image symbol issue

- public/js/lib/svgeditor/recalculate.js
https://app.clickup.com/t/3pht88n
> Fix text position bug after rotate

- src/web/app/actions/beambox/constant.ts
- src/web/app/constants/tutorial-constants.tsx
https://app.clickup.com/t/3qzg9c5
> Fix tutorial hint box positioning issue

- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/views/beambox/Camera-Calibration.tsx
- src/web/app/views/beambox/Diode-Calibration.tsx
- src/web/helpers/device-error-handler.ts
- src/web/interfaces/ILang.d.ts
https://app.clickup.com/t/3qzr8yr
> Fix error handling in calibration

- src/web/app/svgedit/operations/clipboard.ts
Fix copied ref style issue because id selector is old ref id
> Fix copied ref style element id

- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/actions/beambox/svgeditor-function-wrapper.ts
- src/web/app/components/beambox/right-panel/LayerPanel.tsx
- src/web/helpers/api/svg-laser-parser.ts
> Remove svg version warning

- src/web/interfaces/ICommunicator.d.ts
- src/web/interfaces/INetwork.d.ts
remove unused function,
Add new functions
> Update some interfaces

- src/web/app/svgedit/operations/pathActions.ts
- src/web/app/svgedit/path/Path.ts
- src/web/app/svgedit/path/PathNodePoint.ts
- src/web/app/views/beambox/Right-Panels/PathEditPanel.spec.tsx
- src/web/app/views/beambox/Right-Panels/PathEditPanel.tsx
- src/web/interfaces/ISVGPath.d.ts
1. fix add path node when path segment is exactly 2
2. fix control point display when deleting 2 node segment
3. disable disconnecting edge node
> Fix some path action bugs

- src/web/app/components/beambox/path-preview/PathPreview.tsx
- src/web/app/components/beambox/right-panel/__snapshots__/ColorPickerPanel.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/AboutBeamStudio.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/ChangeLog.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/FirmwareUpdate.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/FluxIdLogin.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/MediaTutorial.spec.tsx.snap
- src/web/app/views/beambox/Right-Panels/__snapshots__/PathEditPanel.spec.tsx.snap
- src/web/app/views/beambox/__snapshots__/NetworkTestingPanel.spec.tsx.snap
- src/web/app/views/dialogs/__snapshots__/AlertAndProgress.spec.tsx.snap
- src/web/app/views/dialogs/__snapshots__/Prompt.spec.tsx.snap
- src/web/app/views/monitor/__snapshots__/MonitorControl.spec.tsx.snap
- src/web/app/views/monitor/__snapshots__/MonitorTask.spec.tsx.snap
- src/web/app/widgets/__snapshots__/InputLightbox.spec.tsx.snap
- yarn.lock
fix autofocus homing even though z is not set in `pathpreview startHere`
> Fix autofocus homing when z is not set

- src/web/app/components/beambox/right-panel/__snapshots__/ColorPickerPanel.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/AboutBeamStudio.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/ChangeLog.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/FirmwareUpdate.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/FluxIdLogin.spec.tsx.snap
- src/web/app/components/dialogs/__snapshots__/MediaTutorial.spec.tsx.snap
- src/web/app/views/beambox/Right-Panels/__snapshots__/PathEditPanel.spec.tsx.snap
- src/web/app/views/beambox/__snapshots__/NetworkTestingPanel.spec.tsx.snap
- src/web/app/views/dialogs/__snapshots__/AlertAndProgress.spec.tsx.snap
- src/web/app/views/dialogs/__snapshots__/Prompt.spec.tsx.snap
- src/web/app/views/monitor/__snapshots__/MonitorControl.spec.tsx.snap
- src/web/app/views/monitor/__snapshots__/MonitorTask.spec.tsx.snap
- src/web/app/widgets/__snapshots__/InputLightbox.spec.tsx.snap
- src/web/setupTests.ts
handle version dependent hash in snapshot in unit testing.
> Add snapshot serializer for antd class

- jest.config.js
- package.json
- src/web/app/views/beambox/ImageTracePanel/ImageTracePanel.test.tsx
- src/web/app/views/beambox/ImageTracePanel/StepCrop.test.tsx
- src/web/app/views/beambox/ImageTracePanel/StepTune.test.tsx
- src/web/app/views/beambox/ImageTracePanel/StepTune.tsx
- src/web/app/views/beambox/ImageTracePanel/__snapshots__/ImageTracePanel.test.tsx.snap
- src/web/app/views/beambox/ImageTracePanel/__snapshots__/StepCrop.test.tsx.snap
- src/web/app/views/beambox/ImageTracePanel/__snapshots__/StepTune.test.tsx.snap
- src/web/helpers/image-trace-panel/trace-and-import-path.test.ts
- src/web/helpers/image-trace-panel/trace-and-import-path.ts
- yarn.lock
> Add image trace panel test

- src/web/app/actions/beambox/menuDeviceActions.tsx
- src/web/app/views/beambox/Right-Panels/PathEditPanel.tsx
- src/web/app/views/beambox/Right-Panels/__snapshots__/PathEditPanel.spec.tsx.snap
- src/web/app/widgets/EngraveDpiSlider.tsx
- src/web/app/widgets/__snapshots__/EngraveDpiSlider.spec.tsx.snap
as title.
https://app.clickup.com/t/8669j9zxt
https://app.clickup.com/t/8669ja00v
https://app.clickup.com/t/8669j9zab
> Fix some layout issue

- src/web/app/actions/dialog-caller.tsx
- src/web/app/pages/_connection_setting_page.scss
- src/web/app/views/beambox/ImageEditPanel/CropPanel.spec.tsx
- src/web/app/views/beambox/ImageEditPanel/CropPanel.tsx
- src/web/app/views/beambox/ImageEditPanel/__snapshots__/CropPanel.spec.tsx.snap
- src/web/app/views/beambox/Photo-Edit-Panel.tsx
- src/web/app/views/beambox/Right-Panels/ActionsPanel.spec.tsx
- src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
- src/web/helpers/image-edit-panel/calculate-base64.spec.ts
- src/web/helpers/image-edit-panel/calculate-base64.ts
- src/web/helpers/image-edit-panel/handle-finish.spec.ts
- src/web/helpers/image-edit-panel/handle-finish.ts
- src/web/helpers/image-edit-panel/preprocess.spec.ts
- src/web/helpers/image-edit-panel/preprocess.ts
- src/web/helpers/useI18n.ts
- src/web/interfaces/IImage.d.ts
fix https://app.clickup.com/t/8669j9zky
extract [crop](https://github.com/flux3dp/beam-studio-core/blob/feature/refactor-image-crop/src/web/app/views/beambox/ImageEditPanel/CropPanel.tsx) from [photo-edit-panel ](https://github.com/flux3dp/beam-studio-core/blob/feature/refactor-image-crop/src/web/app/views/beambox/Photo-Edit-Panel.tsx)and refactor it.
> Refactor image crop

- src/web/app/actions/beambox/beambox-init.ts
- src/web/app/components/settings/Camera.tsx
- src/web/app/pages/Beambox.tsx
- src/web/app/pages/GoogleOAuth.tsx
- src/web/app/views/tutorials/tutorialController.ts
- src/web/helpers/open-file-helper.spec.ts
- src/web/helpers/open-file-helper.ts
- src/web/interfaces/IFileSystem.d.ts
allow user to open software by file
> Add Open by File

- public/js/lib/svgeditor/svgutils.js
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/svgedit/operations/clipboard.ts
Fix pasting use with symbol deleted
https://app.clickup.com/t/gnrj6e
> Fix paste deleted use

- src/web/app/actions/beambox/beambox-init.ts
- src/web/helpers/api/cloud.spec.ts
- src/web/helpers/api/cloud.ts
- src/web/helpers/api/discover.ts
- src/web/helpers/api/flux-id.ts
- src/web/interfaces/IStorage.d.ts
> Add beam studio activity

- src/web/app/components/beambox/top-bar/FrameButton.module.scss
- src/web/app/components/beambox/top-bar/FrameButton.tsx
- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/icons/icons.tsx
- src/web/app/views/beambox/Right-Panels/DimensionPanel.tsx
- src/web/interfaces/ISVGCanvas.d.ts
> Add frame button

- src/web/app/components/settings/AdorModule.spec.tsx
- src/web/app/components/settings/AdorModule.tsx
- src/web/app/components/settings/__snapshots__/AdorModule.spec.tsx.snap
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/pages/Settings.tsx
- src/web/app/svgedit/operations/import/appendUseElement.ts
- src/web/app/svgedit/operations/import/importSvg.ts
- src/web/app/svgedit/operations/import/importSvgString.ts
- src/web/helpers/layer-module/layer-module-helper.ts
- src/web/helpers/layer/layer-config-helper.spec.ts
- src/web/helpers/layer/layer-config-helper.ts
- src/web/interfaces/ILang.d.ts
Add default laser module in preference settings.
When workarea is Ador, new layer will use the default laser module
> Add default laser module

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/components/dialogs/DocumentSettings.spec.tsx
- src/web/app/components/dialogs/DocumentSettings.tsx
- src/web/app/lang/de.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/app/svgedit/operations/changeWorkarea.spec.ts
- src/web/app/svgedit/operations/changeWorkarea.ts
- src/web/app/svgedit/operations/import/importBvg.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/helpers/beam-file-helper.ts
- src/web/helpers/device/fit-device-workarea-alert.ts
- src/web/interfaces/ILang.d.ts
1. Add alert when reading bvg with printing layer
2. Update ConnectUsb wording as well.
> Handle read bvg from ador

- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/constants/tutorial-constants.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigPanel.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigSlider.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigSlider.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/__snapshots__/Backlash.spec.tsx.snap
- src/web/app/views/beambox/Right-Panels/ConfigPanel/__snapshots__/ConfigSlider.spec.tsx.snap
Fix：
1. SelectedElement 單獨抽成一個 context 後，Top bar Element title 找不到 SelectedElement
2. 部分 New Interface Tutorial Lang key 沒有對應的翻譯
3. Antd slider 不吃 id
> fix e2e error

- src/web/app/actions/beambox/constant.ts
- src/web/app/components/beambox/right-panel/LayerPanel.tsx
- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/components/boxgen/Boxgen.module.scss
- src/web/app/components/boxgen/Boxgen.tsx
- src/web/app/components/boxgen/Controller.tsx
- src/web/app/components/dialogs/myCloud/MyCloud.tsx
- src/web/app/contexts/CanvasContext.tsx
- src/web/app/views/beambox/ShapePanel/ShapePanel.tsx
- src/web/helpers/absolute-position-helper.spec.ts
- src/web/helpers/absolute-position-helper.ts
- src/web/helpers/announcement-helper.ts
Fix topbar render error
Fix titlebar not updated
Fix Boxgen modal height
Fix "full-screen" floating panel height(mobile)
Allow skipping announcement helper in e2e
> Fix errors for Windows desktop & skip announcement for e2e

- src/web/app/actions/beambox/font-funcs.ts
- src/web/app/components/beambox/top-bar/ElementTitle.module.scss
- src/web/app/components/beambox/top-bar/ElementTitle.tsx
- src/web/app/components/beambox/top-bar/UserAvatar.module.scss
- src/web/app/components/beambox/top-bar/__snapshots__/ElementTitle.spec.tsx.snap
- src/web/app/components/boxgen/Boxgen.module.scss
Fix color of default User avatar icon
Fix position of User avatar, Camera Preview button and Element Name
Fix total height of boxgen left controller
Fix desktop substitute web font even if web font support all char
> Fix windows desktop topbar and font substitute

- src/web/app/views/beambox/Right-Panels/ConfigPanel/AutoFocus.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/AutoFocus.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/Backlash.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/Backlash.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigPanel.module.scss
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigPanel.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigPanelContext.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigValueDisplay.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/Diode.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/Diode.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/InkBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/InkBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ModuleBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ModuleBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/MultipassBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/MultipassBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/PowerBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/PowerBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/RepeatBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/RepeatBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/SaveConfigButton.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/SpeedBlock.spec.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/SpeedBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/UVBlock.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/WhiteInkCheckbox.tsx
- src/web/helpers/layer/layer-config-helper.spec.ts
- src/web/helpers/layer/layer-config-helper.ts
https://app.clickup.com/t/86enqveav
> Add history of layer param operations

- src/web/app/actions/canvas/prespray-area.spec.ts
- src/web/app/actions/canvas/prespray-area.ts
- src/web/helpers/api/svg-laser-parser.ts
Hide prespray area when rotary mode is on.
Fix rotary mode prespray area position.
> Update rotary prespray

- public/js/lib/svgeditor/coords.js
- public/js/lib/svgeditor/recalculate.js
https://app.clickup.com/t/86enqxx9m
> Fix polygon center not updated in recalculate

- src/web/app/components/boxgen/BoxSelector.tsx
- src/web/app/components/boxgen/Controller.tsx
- src/web/app/components/dialogs/CartridgeSettingPanel.tsx
- src/web/app/components/dialogs/DocumentSettings.tsx
- src/web/app/components/dialogs/myCloud/Head.tsx
- src/web/app/views/beambox/ImageEditPanel/CropPanel.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ConfigPanel.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/ModuleBlock.tsx
- src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions.tsx
- src/web/app/views/beambox/Right-Panels/Options-Blocks/TextOptions/VerticalAlignBlock.tsx
- src/web/app/views/beambox/ToolPanels/OffsetModal.tsx
- src/web/app/widgets/AntdSelect.tsx
https://app.clickup.com/t/86ep3ye9v
> Fix antd select placement

- src/web/app/svgedit/svgcanvas.ts
https://flux3dp.slack.com/archives/C03EYFTC1/p1713323693955029?thread_ts=1712886666.269649&cid=C03EYFTC1
> Fix when isUsingDiode is undefined

- src/web/app/components/dialogs/__snapshots__/DocumentSettings.spec.tsx.snap
- src/web/app/constants/workarea-constants.ts
- src/web/app/svgedit/operations/import/importBvg.ts
- src/web/app/svgedit/workarea.ts
- src/web/app/views/monitor/MonitorTask.module.scss
- src/web/helpers/api/svg-laser-parser.ts
1. Add default travel speed, printing padding for ador rotary task.
2. Fix svgcontent viewbox changed after reading extended rotary beam file
> Add rotary task default parameters

- src/web/app/actions/beambox/beambox-init.ts
- src/web/app/actions/beambox/menuActions.ts
https://app.clickup.com/t/86enwert8
> Reduce init pop-ups

- src/web/app/actions/beambox/export-funcs.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/components/beambox/top-bar/FileName.spec.tsx
- src/web/app/components/beambox/top-bar/FileName.tsx
- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/components/beambox/top-bar/__snapshots__/FileName.spec.tsx.snap
- src/web/app/components/dialogs/myCloud/SaveFileModal.spec.tsx
- src/web/app/components/dialogs/myCloud/SaveFileModal.tsx
- src/web/app/contexts/CanvasContext.tsx
- src/web/app/contexts/MyCloudContext.tsx
- src/web/app/svgedit/currentFileManager.spec.ts
- src/web/app/svgedit/currentFileManager.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/views/beambox/TopBar/contexts/TopBarController.spec.tsx
- src/web/app/views/beambox/TopBar/contexts/TopBarController.tsx
- src/web/helpers/file-export-helper.ts
- src/web/interfaces/ISVGCanvas.d.ts
> Add current file manager

- src/web/app/components/beambox/right-panel/Tab.tsx
- src/web/app/components/beambox/right-panel/__snapshots__/Tab.spec.tsx.snap
> Add shortcut hint texts on layer/object tab

- src/web/helpers/color/setElementsColor.ts
fix when attrFill is `undefined`
> Fix set elements color

- package.json
- src/web/app/components/beambox/left-panel/PreviewToolButtonGroup.spec.tsx
- src/web/app/components/beambox/left-panel/PreviewToolButtonGroup.tsx
- src/web/app/components/beambox/left-panel/__snapshots__/PreviewToolButtonGroup.spec.tsx.snap
- src/web/app/views/monitor/Monitor.spec.tsx
- src/web/app/views/monitor/Monitor.tsx
- src/web/app/views/monitor/__snapshots__/Monitor.spec.tsx.snap
- src/web/helpers/locale-helper.spec.ts
- src/web/helpers/locale-helper.ts
- yarn.lock
as title 
https://app.clickup.com/5719332/v/l/6-901802193165-1
> Add locale helper and hide camera feed for NA

- package.json
- src/web/app/views/beambox/SvgNestButtons.module.scss
- src/web/app/views/beambox/SvgNestButtons.tsx
1. [chore: add package-manager field and sort package.json](https://github.com/flux3dp/beam-studio-core/commit/802591e4911e64d2de01ef84a87d0be8639490e6)
2. [fix: reposition svg-nest-button](https://github.com/flux3dp/beam-studio-core/commit/2adfa7c2630c17b653abc0b7cadfa09fd0392d0f) [[clickup]](https://app.clickup.com/t/86ephaz24)
also, remove svg_nest_buttons.scss on both [beam-studio](https://github.com/flux3dp/beam-studio/pull/308) and [beam-studio-web](https://github.com/flux3dp/beam-studio-web/pull/209)
> fix: smart nest button position

- src/web/app/components/dialogs/DocumentSettings.spec.tsx
- src/web/app/components/dialogs/DocumentSettings.tsx
- src/web/app/components/dialogs/__snapshots__/DocumentSettings.spec.tsx.snap
- src/web/app/constants/workarea-constants.ts
- src/web/app/lang/cs.ts
- src/web/app/lang/da.ts
- src/web/app/lang/de.ts
- src/web/app/lang/el.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/id.ts
- src/web/app/lang/it.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/ms.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/no.ts
- src/web/app/lang/pl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/se.ts
- src/web/app/lang/th.ts
- src/web/app/lang/vi.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/interfaces/ILang.d.ts
Rename workarea to machine in document settings panel.
Add workarea select in document settings panel if dimension if customizable.
[clickup](https://app.clickup.com/t/86eq71eww)
[figma](https://www.figma.com/design/hYEM7EUfjR6NZt9meMzxDp/Beam-Studio-App?node-id=6120-5978&node-type=canvas)
> Support Promark customized dimension

- src/web/app/actions/dialog-caller.tsx
- src/web/app/svgedit/operations/import/importSvg.ts
1. [feat: add cache on import svg's radio select](https://github.com/flux3dp/beam-studio-core/commit/d2dc146e4183859fd8958f001c5e0d1464cd3019) [[clickup]](https://app.clickup.com/t/86eptz72m)
> feat: add cache on import svg's radio select

- src/web/app/constants/add-on.ts
- src/web/helpers/api/svg-laser-parser.ts
- src/web/helpers/device/framing.ts
- src/web/helpers/device/get-rotary-ratio.spec.ts
- src/web/helpers/device/get-rotary-ratio.ts
Fix y ratio not applied when framing with chuck rotary.
Extract get y ratio calculation
> Fix framing rotary y ratio

- src/web/app/actions/beambox/constant.ts
- src/web/app/components/beambox/path-preview/PathPreview.tsx
- src/web/app/components/beambox/right-panel/LayerPanel.tsx
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/index.tsx
- src/web/app/components/dialogs/myCloud/MyCloud.tsx
- src/web/app/constants/layout-constants.ts
- src/web/app/constants/tutorial-constants.tsx
- src/web/app/constants/workarea-constants.ts
- src/web/app/svgedit/workarea.ts
- src/web/app/views/beambox/Photo-Edit-Panel.tsx
- src/web/app/views/beambox/ShapePanel/ShapePanel.tsx
- src/web/app/widgets/DraggableModal.tsx
- src/web/app/widgets/FullWindowPanel/FullWindowPanel.tsx
- src/web/helpers/absolute-position-helper.spec.ts
- src/web/helpers/absolute-position-helper.ts
1. Add DraggableModal
2. Extract layout constants from constants
> Add draggable modal

- src/web/helpers/device/framing.ts
> Fix using invisible layers

- src/web/helpers/api/svg-laser-parser.ts
- src/web/helpers/job-origin.spec.ts
- src/web/helpers/job-origin.ts
add ref module to compensate module offset when using job origin
> Fix job origin with modules

- src/web/app/svgedit/interaction/mouseInteractions.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/helpers/layer/layer-helper.ts
1. [feat(svgedit): add layers selection when multi-select](https://github.com/flux3dp/beam-studio-core/commit/319300d484a37bd42b70543a14932bee0a248175)
2. style: use linter and prettier to attack svgcanvas
> feat(svgedit): add layers selection when multi-select

- src/web/app/actions/beambox/export-funcs-swiftray.ts
- src/web/app/components/beambox/top-bar/FrameButton.spec.tsx
- src/web/app/components/beambox/top-bar/FrameButton.tsx
- src/web/app/components/beambox/top-bar/GoButton.tsx
- src/web/app/components/dialogs/FramingModal.tsx
- src/web/app/constants/keycode-constants.ts
- src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
- src/web/app/views/beambox/Right-Panels/__snapshots__/ActionsPanel.spec.tsx.snap
- src/web/helpers/shortcuts.ts
1. Fix new version swiftray framing error when layer title is not found.
2. Add F1: framing, F2: go shortcuts, F1 for promark only, F2 for all devices.
3. Move image action trapezoid out from dev mode.
> Add promark shortcuts

- src/web/helpers/device/framing.ts
1. Fix bb2 rotary not using a-axis.
2. Update red light behavior:
i. Turn off before moving to first position.
ii. Turn on after finishing.
> Fix bb2 framing

- src/web/app/constants/connection-constants.ts
- src/web/app/lang/de.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/no.ts
- src/web/app/lang/se.ts
- src/web/helpers/device-master.ts
Promark serial may not be updated at the first time.
Therefore, add retry and wait to make sure serial is updated.
Also, fix translations for anti-aliasing.
> Fix promark serial not updated at the first time

- src/web/app/components/dialogs/camera/PromarkCalibration.tsx
change promark calibration chessboard size to fix asymmetric issue
> Change promark calibration chessboard size

- src/web/helpers/layer/layer-config-helper.ts
Fix postPresetChange when some limit field is undefined
> Fix postPresetChange when some field limit is undefined

- src/web/app/components/dialogs/DocumentSettings.spec.tsx
- src/web/app/components/dialogs/DocumentSettings.tsx
- src/web/app/components/dialogs/__snapshots__/DocumentSettings.spec.tsx.snap
- src/web/app/components/dialogs/promark/PromarkSettings.spec.tsx
- src/web/app/components/dialogs/promark/PromarkSettings.tsx
- src/web/helpers/api/control.ts
- src/web/helpers/api/swiftray-client.ts
- src/web/helpers/api/swiftray-control.ts
- src/web/helpers/device-master.ts
- src/web/interfaces/IControlSocket.d.ts
1. Add set field function in swiftray client
2. Move Promark out from dev options in document settings
> Add set field calibration

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/components/beambox/top-bar/Menu.tsx
- src/web/app/lang/cs.ts
- src/web/app/lang/da.ts
- src/web/app/lang/de.ts
- src/web/app/lang/el.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/id.ts
- src/web/app/lang/it.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/ms.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/no.ts
- src/web/app/lang/pl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/se.ts
- src/web/app/lang/th.ts
- src/web/app/lang/vi.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/interfaces/ILang.d.ts
Related PR:
[[beam-studio]](https://github.com/flux3dp/beam-studio/pull/315)
> feat: add promark example

- src/web/app/components/dialogs/DocumentSettings.spec.tsx
- src/web/app/components/dialogs/DocumentSettings.tsx
- src/web/app/components/dialogs/RotarySettings.spec.tsx
- src/web/app/components/dialogs/RotarySettings.tsx
- src/web/app/components/settings/Editor.tsx
- src/web/app/components/settings/__snapshots__/Editor.spec.tsx.snap
- src/web/app/pages/SelectMachineModel.tsx
- src/web/helpers/locale-helper.spec.ts
- src/web/helpers/locale-helper.ts
1. Add beta in calculation_optimization
2. Add `isTwOrHk` in locale helper and apply for promark and chuck
> Change for 2.4.3 release

- src/web/helpers/locale-helper.ts
1. [feat(helpers): update locale-helper to use navigator.languages as the default locale source](https://github.com/flux3dp/beam-studio-core/commit/74dda8650bc76fb5dcb47b08b72d7502739d5e40)
> feat(helpers): update locale-helper to use navigator.languages

- src/web/app/components/dialogs/CodeGenerator/BarcodeGenerator.tsx
- src/web/app/components/dialogs/CodeGenerator/svgOperation.ts
- src/web/app/svgedit/svgcanvas.ts
- src/web/app/views/beambox/Right-Panels/ActionsPanel.tsx
- src/web/interfaces/ISVGCanvas.d.ts
1. [feat(code-generator): add invert color on barcode generator](https://github.com/flux3dp/beam-studio-core/commit/278e05b1b853144b70bfd3170ac229ead2251e92) [(clickup)](https://app.clickup.com/t/86eqq9r19)
> feat: barcode invert color

- src/web/app/lang/cs.ts
- src/web/app/lang/da.ts
- src/web/app/lang/de.ts
- src/web/app/lang/el.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/id.ts
- src/web/app/lang/it.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/ms.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/no.ts
- src/web/app/lang/pl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/se.ts
- src/web/app/lang/th.ts
- src/web/app/lang/vi.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
1. Change to [(link)](https://support.flux3dp.com/hc/zh-tw/articles/11318820440591)
> feat(lang): revise promark hint links

- src/web/app/svgedit/operations/clipboard.ts
1. [fix(svgedit): update orig-image if blob url is not reachable](https://github.com/flux3dp/beam-studio-core/commit/51bc8d3a007eac6fcbf55abecee8de8fde1f3a40)
> fix(svgedit): update orig-image if blob url is not reachable

- src/web/app/actions/camera/preview-helper/BB2PreviewManager.ts
- src/web/app/actions/camera/preview-helper/BasePreviewManager.ts
- src/web/app/actions/camera/preview-helper/BeamPreviewManager.ts
- src/web/app/lang/cs.ts
- src/web/app/lang/da.ts
- src/web/app/lang/de.ts
- src/web/app/lang/el.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/id.ts
- src/web/app/lang/it.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/ms.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/no.ts
- src/web/app/lang/pl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/se.ts
- src/web/app/lang/th.ts
- src/web/app/lang/vi.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/interfaces/ILang.d.ts
- src/web/interfaces/PreviewManager.d.ts
1. feat(camera): add pause event if click 'esc' during preview [[clickup]](https://app.clickup.com/t/86eqar67z)
> feat: camera preview pause

- src/web/app/actions/beambox/svg-editor.ts
1. [feat(actions): alert 801 if import svg in web but no machine connection](https://github.com/flux3dp/beam-studio-core/commit/3362a374af5859e764b9b4d5b71fb36b50970dd2) [[clickup]](https://app.clickup.com/t/86eqfqdtv)
> feat(actions): alert 801 if import svg in web but no machine connection

- src/web/app/components/dialogs/MaterialTestGeneratorPanel/BlockSetting.spec.ts
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/BlockSetting.ts
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/TableSetting.ts
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/TableSettingForm.tsx
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/generateSvgInfo.ts
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/index.tsx
1. add fill interval setting on promark series on engrave
2. revise minimum value of block setting
3. rotate row info text by 90 degree
> feat: add fill interval on promark series

- src/web/app/actions/beambox/export-funcs.ts
- src/web/app/components/beambox/top-bar/GoButton.tsx
1. [feat(top-bar): add throttle on go button, block if dialog or progress id is exist](https://github.com/flux3dp/beam-studio-core/commit/6ce83a28afcdeb19a38b559f56a83fed6b4d5965) [[clickup]](https://app.clickup.com/t/86eqj59w4)
> fix: go button only once

- src/web/helpers/api/svg-laser-parser.ts
- src/web/interfaces/ITaskConfig.ts
Add `safe_height` for traveling
> Update curve engraving config data

- src/web/app/components/dialogs/camera/BB2Calibration.tsx
- src/web/app/components/dialogs/camera/common/SolvePnP.tsx
- src/web/helpers/api/camera-calibration.ts
- src/web/helpers/camera-calibration-helper.ts
Add interest area in camera calibration solve pnp step
(ghost changes: https://github.com/flux3dp/fluxghost/pull/92/files)
[clickup](https://app.clickup.com/t/86eqx4hxr)
> Add interest area in solve pnp

- src/web/helpers/api/svg-laser-parser.ts
> Fix curve safe height calculation

- src/web/app/components/beambox/left-panel/DrawingToolButtonGroup.tsx
- src/web/app/components/beambox/left-panel/__snapshots__/DrawingToolButtonGroup.spec.tsx.snap
- src/web/app/components/dialogs/CurveEngraving/CurveEngraving.tsx
- src/web/helpers/device/curve-measurer/raw.ts
- src/web/helpers/device/curve-measurer/red-light.ts
Fixed:
1. measurer setupDevice no await
2. Change curve engraving antd motion timeout to 0.5
3. Update drawing tool button order
> Fix red light measure issue

- src/web/app/components/beambox/top-bar/TopBar.module.scss
- src/web/app/constants/tutorial-constants.tsx
- src/web/helpers/absolute-position-helper.spec.ts
- src/web/helpers/absolute-position-helper.ts
fix tutorial position due to go button text removed
also update topbar drag region for mac
> Fix tutorial constants

- src/web/app/components/beambox/top-bar/TopBar.module.scss
- src/web/app/components/beambox/top-bar/TopBar.tsx
remove top bar drag for non-mac os
> Fix top bar drag

- src/web/helpers/api/swiftray-client.ts
- src/web/helpers/api/swiftray-control.ts
- src/web/helpers/device-master.ts
- src/web/helpers/device/framing.ts
- Framing
- Frame with corner points to save time
- Add connecting message (setGalvoParameters)
- Fix bugs of FramingType.Framing and FramingType.Hull
-  Add swiftray connection warning for each request when connection fail
[clickup](https://app.clickup.com/t/86eqzk5yt)
> Fix framing

- src/web/app/actions/tabController.ts
as title, only send event if title changed
> Remove unnecessary SetTabTitle event

- src/web/app/components/beambox/top-bar/TopBar.module.scss
- src/web/app/components/beambox/top-bar/TopBar.tsx
fix drag area blocking devtool
> Fix mac topbar drag area

- src/web/app/components/ImageEditPanel/components/TopBar/index.tsx
- src/web/app/components/ImageEditPanel/index.tsx
- src/web/app/lang/cs.ts
- src/web/app/lang/da.ts
- src/web/app/lang/de.ts
- src/web/app/lang/el.ts
- src/web/app/lang/en.ts
- src/web/app/lang/es.ts
- src/web/app/lang/fi.ts
- src/web/app/lang/fr.ts
- src/web/app/lang/id.ts
- src/web/app/lang/it.ts
- src/web/app/lang/ja.ts
- src/web/app/lang/kr.ts
- src/web/app/lang/ms.ts
- src/web/app/lang/nl.ts
- src/web/app/lang/no.ts
- src/web/app/lang/pl.ts
- src/web/app/lang/pt.ts
- src/web/app/lang/se.ts
- src/web/app/lang/th.ts
- src/web/app/lang/vi.ts
- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
- src/web/interfaces/ILang.d.ts
1.[feat(lang): add i18n for image-edit-panel topbar buttons](https://github.com/flux3dp/beam-studio-core/commit/137eea38faca9ae605b802264ba887506a55426b)
> feat(lang): add i18n for image-edit-panel topbar buttons

- src/web/app/actions/beambox/preview-mode-controller.ts
- src/web/app/contexts/CalibrationContext.tsx
- src/web/app/views/beambox/CameraCalibration/StepBeforeAnalyzePicture.tsx
- src/web/app/views/beambox/Diode-Calibration.tsx
wait for raw mode exit for `PreviewModeController.end` if there is following command during calibraition
> Fix preview mode end when camera calibration set config

- src/web/helpers/api/swiftray-client.ts
Related to [swiftray PR](https://github.com/flux3dp/swiftray/pull/449)
> Fix promark framing workare size

- src/web/app/actions/beambox/export-funcs-swiftray.ts
- src/web/app/actions/beambox/export-funcs.ts
- src/web/app/components/beambox/path-preview/SidePanel.spec.tsx
- src/web/app/components/beambox/path-preview/SidePanel.tsx
- src/web/app/components/beambox/path-preview/__snapshots__/SidePanel.spec.tsx.snap
- src/web/app/widgets/UnitInput.tsx
- src/web/helpers/shortcuts.ts
[Swiftray](https://github.com/flux3dp/swiftray/pull/450)
> Add path preview and hide 'Start Here' for Swiftray

- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/components/beambox/left-panel/LeftPanel.tsx
- src/web/app/components/dialogs/FramingModal.module.scss
- src/web/app/components/dialogs/PresetsManagementPanel/PresetsManagementPanel.module.scss
- src/web/app/components/dialogs/myCloud/GridFile.tsx
- src/web/app/components/dialogs/promark/ZAxisAdjustment.module.scss
- src/web/app/views/beambox/NetworkTestingPanel.tsx
- src/web/app/views/beambox/__snapshots__/NetworkTestingPanel.spec.tsx.snap
- src/web/app/widgets/UnitInput.tsx
- src/web/helpers/shortcuts.ts
- src/web/styles/_mixins.scss
1. Fix shortcut with inputs
2. Fix shortcut behavior when window blur
3. Fix modal buttons margin
> Fix shortcut

- src/web/app/components/beambox/top-bar/TopBar.module.scss
- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/components/beambox/top-bar/tabs/Tabs.module.scss
Fix multi tab drag-area blocking issue by tab focus/blur event
Change the whole top bar to drag area if tab focused & is mac
> Fix topbar drag area blocking issue

- src/web/app/actions/beambox/export-funcs-swiftray.ts
- src/web/interfaces/ITaskConfig.ts
Send correct config to calculate real time
> Fix estimated time in path preview by swiftray

- src/web/helpers/clipper/getClipperLib.ts
as title, fix getClipperLib according to clipper_unminified
> Fix get clipper lib in worker

- src/web/app/components/ImageEditPanel/index.tsx
- src/web/helpers/shortcuts.ts
And remove string version scope
> Fix unsubscribing wrong shortcuts when changing scopes

- src/keyboard.d.ts
- src/web/helpers/shortcuts.ts
as title, fix shortcut for IME (ex: 注音)
> Fix shortcut for IME

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/components/beambox/top-bar/Menu.tsx
1. [feat(menu): add bb2 material test](https://github.com/flux3dp/beam-studio-core/commit/4db91227a07fc2e61a5fb9c6162ccc66f4ddafe2)
2. [feat(menu): make promark, bb2 invisible on web](https://github.com/flux3dp/beam-studio-core/commit/8545f745d5cf3a1f23558f4670b1f29e26b6b1ad)
1.https://github.com/flux3dp/beam-studio/pull/337
> feat(menu): add bb2 material test

- src/web/assets/fcode/promark-calibration-110.bvg
- src/web/assets/fcode/promark-calibration-150.bvg
- src/web/assets/fcode/promark-calibration-220.bvg
- src/web/helpers/device/promark/calibration.ts
as title, [clickup](https://app.clickup.com/t/86er98jgm)
> Update config for promark camera calibration
