- .github/workflows/basic-check.yml
- .github/workflows/repository-dispatch.yml
Once there is a new merge into master, it will fire an event called **core_merged** that is listened by the web workflow which will run e2e tests and make auto deployment. Therefore ideally we can ensure any changes in core are supposed not to break any e2e tests.
> trigger web workflow once the core has a new commit merged into master

- .github/workflows/basic-check.yml
originally, `unit-test` and `coverage` these two jobs would cover duplicate task which is to ensure all unit tests get passed. So now, merge them together in order to save CI execution time.
> merge unit test with coverage check

- src/web/app/actions/beambox/font-funcs.ts
remove `communicator` based functions, using font helper only.
related PR: https://github.com/flux3dp/beam-studio/pull/247
> Update font functions

- src/web/app/components/beambox/top-bar/TopBar.tsx
- src/web/app/constants/tutorial-constants.tsx
- src/web/app/views/dialogs/__snapshots__/NonStopProgress.spec.tsx.snap
- src/web/app/views/tutorials/TutorialContext.tsx
- src/web/helpers/absolute-position-helper.spec.ts
- src/web/helpers/absolute-position-helper.ts
1. Auto start camera preview without clicks
2. Topbar right buttons position without path preview button
3. Hide path preview button tutorial
4. Scroll right panel and change box/dialog position of preset selector according to window height
> Fix tutorial of Ador

- src/web/app/components/dialogs/MaterialTestGeneratorPanel/TableSettingForm.tsx
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/TextSettingForm.tsx
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/index.tsx
- src/web/app/svgedit/history/history.ts
- src/web/app/svgedit/history/undoManager.ts
- src/web/interfaces/ISVGCanvas.d.ts
1. [perf(dialogs): only trigger update-layer-panel when on-export](https://github.com/flux3dp/beam-studio-core/commit/aa820f60ebce4efaf06e4d6f1245be824fcb41d1)
2. [feat(svgedit-history): remove un-apply method from undo-manager](https://github.com/flux3dp/beam-studio-core/commit/8788938614025a835ae4c362be46d0910607b4bb)
3. [feat: add identify-layers to svgcanvas interface](https://github.com/flux3dp/beam-studio-core/commit/3d2d4b4c677d62cbf295f79101e7438b3d08c554)
4. [feat: make base-history-command can trigger unapply even if no handler](https://github.com/flux3dp/beam-studio-core/commit/5c84dc4219d1420b14432a56e6e7f6397b5eb2d0)
> perf: material test generator preview slow

- src/web/app/components/dialogs/RotarySettings.spec.tsx
- src/web/app/components/dialogs/RotarySettings.tsx
1. [feat(components): rotary settings enable chuck option if locale includes zh-tw](https://github.com/flux3dp/beam-studio-core/commit/e297f61bc3b9f3f1603ed013617e4f43c699bbe5)
> feat:rotary coming soon

- src/web/app/lang/zh-cn.ts
- src/web/app/lang/zh-tw.ts
1. [fix(lang): fix zh-tw zh-cn, promark_hint i18n](https://github.com/flux3dp/beam-studio-core/commit/1567daf1672fd1fa3fcb0842560d2145052b17e5)
> fix: promark hint i18n

- src/__mocks__/app/widgets/Input.tsx
- src/web/app/views/beambox/Layer-Color-Config.tsx
- src/web/app/views/dialogs/Prompt.tsx
- src/web/app/widgets/Input.spec.tsx
- src/web/app/widgets/Input.tsx
- src/web/app/widgets/InputKeyWrapper.tsx
as title, fix setStopEditingInput not called if blur is not triggered.
Which ends up blocking electron shortcuts
> Fix setStopEditingInput if blur not triggered

- src/web/app/components/beambox/top-bar/FrameButton.tsx
Fixed:
1. shortcut not work for non-promark devices
2. shortcut shouldn't work when not in drawing mode.
> Fix framing short cut

- .prettierignore
- public/js/lib/svgeditor/svgutils.js
- src/web/app/actions/beambox/menuActions.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/actions/beambox/svgeditor-function-wrapper.ts
- src/web/app/components/beambox/svg-editor/Workarea.tsx
- src/web/app/components/beambox/top-bar/Menu.tsx
- src/web/app/svgedit/interaction/mouseInteractions.ts
- src/web/app/svgedit/operations/autoFit.ts
- src/web/app/svgedit/operations/clipboard.ts
- src/web/app/views/beambox/Right-Panels/ObjectPanel.tsx
- src/web/app/views/beambox/ToolPanels/ToolPanels.tsx
[[clickup]](https://app.clickup.com/t/86eqmymtv)
1. [feat(svgedit): paste action now based on native clipboard only](https://github.com/flux3dp/beam-studio-core/commit/fbfce1ed7b17b1c7e79300fff37ece57ca275209)
2. [feat(svg-editor): remove update-context-menu's paste update on cut, copy action](https://github.com/flux3dp/beam-studio-core/commit/3e38c7893325fb7a757b333b14d3db28bbd5ecae) 
3. [feat(svgedit): clipboard methods are use native clipboard now](https://github.com/flux3dp/beam-studio-core/commit/15c085bf392bf0866f6373dfb582f5a7151ed3b2)
4. [fix(lib): remove to-lower-case to correctly copy node name](https://github.com/flux3dp/beam-studio-core/commit/40d8292d0c4ef2c35666b44c934e067c360d5607)
5. [fix(svgedit): revise auto-fit to use for loop instead of …
> feat(svgedit): paste action now based on native clipboard only

- src/web/app/pages/ConnectMachineIp/index.tsx
1. [fix(pages): add device-master select during promark test](https://github.com/flux3dp/beam-studio-core/commit/cffd3e2e5159c1065a6082323744d3a3d981c891)
// keep this console.log for debug if the device selection is not succeed.
> fix(pages): add device-master select during promark test

- src/web/app/components/dialogs/PresetsManagementPanel/LaserInputs.spec.tsx
- src/web/app/components/dialogs/PresetsManagementPanel/LaserInputs.tsx
- src/web/app/components/dialogs/PresetsManagementPanel/PresetsManagementPanel.spec.tsx
- src/web/app/components/dialogs/PresetsManagementPanel/PresetsManagementPanel.tsx
- src/web/app/components/dialogs/PresetsManagementPanel/PromarkInputs.tsx
- src/web/app/components/dialogs/PresetsManagementPanel/__snapshots__/LaserInputs.spec.tsx.snap
- src/web/app/components/dialogs/PresetsManagementPanel/__snapshots__/PromarkInputs.spec.tsx.snap
- src/web/helpers/layer/layer-config-helper.ts
1. [fix(component): add default config to each new preset](https://github.com/flux3dp/beam-studio-core/commit/bca41de6bb300238f29a03cfe672becf8f423941) [[clickup]](https://app.clickup.com/t/86eqr16qe)
2. [fix(dialogs): update both z-step and focus-step on editing preset](https://github.com/flux3dp/beam-studio-core/commit/e11d332f13b195a2b5ee6a09f83cec1d16d57eef)
> fix: preset no default

- src/web/helpers/api/flux-id.ts
As title
`next` param in url will take effect after Member center updates
> Update member center link

- src/web/app/widgets/UnitInput.tsx
Because antd ref was changed to `Proxy(HTMLInput)` so editing value is not available.
Use `parentNode?.querySelector` to get the real input
> Fix UnitInput ref for antd 5.22

- src/web/app/actions/beambox/font-funcs.ts
- src/web/helpers/fonts/webFonts.ts
font kit failed to read name of some ttc fonts collections
add `collectionIdx` to webFonts, fall back to first font in ttc if not set
[slack](https://flux3dp.slack.com/archives/C2KV9ULLC/p1733901059899759)
> Fix web font ttc not found

- src/web/app/actions/beambox/beambox-global-interaction.ts
- src/web/app/components/beambox/top-bar/Menu.tsx
- src/web/app/svgedit/operations/import/importSvg.ts
1. [fix(top-bar): disable path menu during selecting bitmap image](https://github.com/flux3dp/beam-studio-core/commit/8ea0b9baa1ceebc2168f92ba6d7f4c2abb42d6af) [[clickup]](https://app.clickup.com/t/86eqy9jx1)
2. [fix(top-bar): disable path menu for svg, dxf object](https://github.com/flux3dp/beam-studio-core/commit/180c02992fc273aea3e5dc2791e9f93a8dad1318)
> fix(top-bar): disable path menu during selecting image, svg, dxf

- src/web/app/svgedit/operations/clipboard.ts
1. [fix(operations): first attempt of generate shapes grid array not work](https://github.com/flux3dp/beam-studio-core/commit/58caae09127869e25d40ae03c0f532f7838d27eb) [[clickup]](https://app.clickup.com/t/86er0ffpr)
> fix(operations): first attempt of generate shapes grid array not work

- package.json
- src/web/app/actions/beambox/font-funcs.ts
- yarn.lock
Fix fontkit text to path for rtl text by: [clickup](https://app.clickup.com/t/86eqzmhen)
1. Getting the start position from `getStartPositionOfChar` or `getEndPositionOfChar` according to direction.
2. Reverse glyph
3. fix some mark position by `run.position`
Known issue:
some mac font may still have offseted mark
> Fix font func for rtl texts

- src/web/app/components/dialogs/MaterialTestGeneratorPanel/TextSetting.ts
- src/web/app/components/dialogs/MaterialTestGeneratorPanel/index.tsx
1. set speed of text setting to 1000 if using promark models
> feat(material-test-generator): set speed of textsetting to 1000

- src/web/app/components/dialogs/promark/PromarkSettings.spec.tsx
- src/web/app/components/dialogs/promark/PromarkSettings.tsx
- src/web/app/components/dialogs/promark/ZAxisAdjustment.tsx
- src/web/app/contexts/MonitorContext.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/FillSettingModal.module.scss
- src/web/app/views/beambox/Right-Panels/ConfigPanel/FillSettingModal.tsx
- src/web/app/views/beambox/Right-Panels/ConfigPanel/__snapshots__/FillSettingModal.spec.tsx.snap
- src/web/helpers/layer/layer-config-helper.spec.ts
- src/web/helpers/layer/layer-config-helper.ts
1. Fill setting modal 說明不用 hover，直接顯示
2. Bi-directional 改預設為開
3. Promark 設定、Z 軸移動，打標的預設功率改為功率 50% , 速度 1000mm/s
5. Swiftray 重開後，再次送工作，預估時長為 0
> Promark feedback

- src/web/app/components/ImageEditPanel/index.tsx
- src/web/app/components/dialogs/myCloud/GridFile.tsx
- src/web/app/widgets/UnitInput.tsx
- src/web/helpers/shortcuts.ts
- 輸入框無法使用左右鍵移動、無法刪除
快捷鍵 default 設定會 preventDefault
先在 UnitInput、雲端檔案名編輯時加上 stopPropagation，避開快捷鍵
（可能仍有部分 input 會和快捷鍵設定衝突
- 圖片進階編輯時，按刪除鍵會刪除圖片；按 E 會跳出元素面板
除了特別設定的快捷鍵，其餘快捷鍵仍會生效
暫時給圖片進階編輯加 scope，禁用其餘快捷鍵
（待確認做法&是否要保留部分快捷鍵
> Fix shortcuts

- src/web/app/actions/beambox/preview-mode-background-drawer.ts
as title, fix for rxjs subscribe change in
https://github.com/flux3dp/beam-studio-core/commit/7b286f54c677a92d959ebb303d8dc1f25d8db6f3#diff-65b9d938812c0c28bdc94b42d8f0f3396fd445d312a9cfa8e8191e94d9cdabecR80
change to arrow function to avoid similar cases
> Fix drawBlobToBackground this issue when called in rxjs

- src/web/app/actions/beambox/menuActions.ts
- src/web/app/actions/beambox/svg-editor.ts
- src/web/app/actions/dialog-caller.tsx
- src/web/app/components/ImageEditPanel/index.tsx
- src/web/app/components/boxgen/Boxgen.tsx
- src/web/helpers/hooks/useNewShortcutsScope.ts
- src/web/helpers/shortcuts.ts
1. change shortcut scope structure to array of array (can also be key -> array pairs but I am afraid of scope new collision)
2. Block editor events from electron accelerator (undo, redo, cut, copy, paste) when not in base scope
> Update shortcut scopes
